"""Adapter metadata and headers for Candidate Code View artifacts."""

from __future__ import annotations

from canvasforge import __version__

CANDIDATE_BANNER = (
    "# CanvasForge Candidate Code View YAML\n"
    "# STATUS: Studio-unvalidated Candidate — do not treat as production source.\n"
    "# Power Apps Studio remains the final validation authority.\n"
    "# DO NOT edit this file manually. Regenerate from the manifest.\n"
    f"# Generated by CanvasForge {__version__}\n"
)


def wrap_candidate_yaml(body: str, *, build_id: str, screen_key: str) -> str:
    header = (
        CANDIDATE_BANNER
        + f"# buildId: {build_id}\n"
        + f"# screen: {screen_key}\n"
        + "# evidence: documented bootstrap (no studio-exported fixture in-repo)\n"
        + "\n"
    )
    return header + body
